texts:
  ja: Inalz
  en: __COPY__
---
texts:
  ja: Inalz は、 Markdown ドキュメントの翻訳をメンテナンス可能にするための i18n ツールです。
  en: Inalz is a Markdown i18n tool for maintainable translation.
---
texts:
  ja: チュートリアル
  en: Tutorial
---
texts:
  ja: Inalz を `npm` でインストールしてください。
  en: Install Inalz with `npm`.
---
texts:
  ja: Inalz を始めるために必要なのは、Markdown ドキュメントと、その翻訳先を指示するための設定ファイル `inalz.yml` です。
  en: To get started with Inalz, you need a Markdown document and a configuration file `inalz.yml`, which directs translation target destinations.
---
texts:
  ja: たとえば、英語の `README.md` を日本語の `README.ja.md` に対応させるためには、以下のような設定を `inalz.yml` に書いて、プロジェクトルートに置きます。
  en: For example, you can create `inalz.yml` to map English `README.md` to Japanese `README.ja.md` as below.
---
texts:
  ja: 例として、次のような `README.md` を書いておきます。
  en: As an example, create `README.md` as follows.
---
texts:
  ja: カレントディレクトリには次の 2 つのファイルがあります。
  en: There are 2 files in the current directory.
---
texts:
  ja: ここで、 Inalz コマンドを実行しましょう。
  en: Then, execute Inalz command.
---
texts:
  ja: "`inalz sync` コマンドは、`inalz.yml` の設定をもとに Locale ファイルを生成します。ここで生成される Locale ファイルは 1 つだけで、`locale` で設定した `.README.yml` です。"
  en: The `inalz sync` command generates Locale files according to `inalz.yml` configuration. Now it generates a single file, `.README.yml` set on `locale`.
---
texts:
  ja: Locale ファイル `.README.yml` は次のようになっているはずです。
  en: The Locale file `.README.yml` should be as below.
---
texts:
  ja: Locale ファイルは、パラグラフ単位での本文と訳文の対応を表しています。デフォルトの `__COPY__` は、元の文章を置き換えずにそのまま使うことを意味しています。
  en: Locale file describes mappings of a source text and a target text by paragraph. Default target text `__COPY__` means to use the source text without replacing.
---
texts:
  ja: "`.README.yml` を次のように編集してみましょう。"
  en: Let's edit `.README.yml` as follows.
---
texts:
  ja: 次に、翻訳ドキュメントファイルを出力します。そのためには別の Inalz コマンドを実行しましょう。
  en: Next, output a translation document file. Execute another Inalz command to do it.
---
texts:
  ja: "`inalz build` コマンドは、Locale ファイルと元ドキュメントを参照して、翻訳ドキュメントを出力します。ここでは `README.ja.md` が出力されます。"
  en: The `inalz build` command generates a translation document by refering to Locale files and source documents. In this case, it generates `README.ja.md`.
---
texts:
  ja: ファイルの内容は次のようになっているはずです。
  en: The file should be as bellow.
---
texts:
  ja: "`README.md` の日本語訳が完成しました！　`README.ja.md` は、元の Markdown ファイルのドキュメント構造を維持しています。`inalz build` コマンドの仕事は単純で、ただ元の Markdown ファイルの文字列を置換するだけです。"
  en: You have done translation of `README.md`! `README.ja.md` maintains the document structure of the source Markdown file. The `inalz build` command does a simple task, to replace texts of the source Markdown file.
