texts:
  ja: Inalz
  en: __COPY__
---
texts:
  ja: Inalz は、 Markdown ドキュメントの翻訳をメンテナンス可能にするための i18n ツールです。
  en: Inalz is a Markdown i18n tool for maintainable translation.
---
texts:
  ja: チュートリアル
  en: Tutorial
---
texts:
  ja: Inalz を `npm` でインストールしてください。
  en: Install Inalz with `npm`.
---
texts:
  ja: Inalz を始めるために最小限必要なのは、Markdown ドキュメントと、その翻訳先を指示するための設定ファイル `inalz.yml` です。
  en: To get started with Inalz, you need a Markdown document and a configuration file `inalz.yml`, which directs translation target destinations.
---
texts:
  ja: たとえば、英語の `README.md` を日本語の `README.ja.md` に対応させるためには、以下のような設定を `inalz.yml`
    に書いて、プロジェクトルートに置きます。
  en: For example, you can create `inalz.yml` to map English `README.md` to Japanese `README.ja.md` as below.
---
texts:
  ja: 例として、次のような `README.md` を書いておきます。
  en: As an example,
---
texts:
  ja: カレントディレクトリには次の 2 つのファイルがあります。
  en: __COPY__
---
texts:
  ja: ここで、 Inalz コマンドを実行しましょう。
  en: __COPY__
---
texts:
  ja: "`inalz sync` コマンドは、`inalz.yml` の設定をもとに Locale ファイルを生成します。ここで生成される Locale
    ファイルは 1 つだけで、`localePath` で設定した``.README.yml` です。"
  en: __COPY__
---
texts:
  ja: 生成された Locale ファイル ``.README.yml`` の中は次のようになっています。
  en: __COPY__
---
texts:
  ja: Locale ファイルは、パラグラフ単位での本文と訳文の対応を表しています。デフォルトの `__COPY__`
    は、元の文章を置き換えずにそのまま使うことを意味しています。
  en: __COPY__
---
texts:
  ja: "`.README.yml` を次のように編集してみましょう。"
  en: __COPY__
---
texts:
  ja: 次に、翻訳ドキュメントファイルを出力します。そのためには別の Inalz コマンドを実行しましょう。
  en: __COPY__
---
texts:
  ja: "`inalz build` コマンドは、Locale ファイルと元ドキュメントを参照して、翻訳ドキュメントを出力します。ここでは
    `README.ja.md` が出力されます。"
  en: __COPY__
---
texts:
  ja: ファイルの内容は次のようになっています。
  en: __COPY__
---
texts:
  ja: "`README.md` の日本語訳が完成しました！　`README.ja.md` は、元の Markdown
    ファイルのドキュメント構造を維持しています。`inalz build` コマンドの仕事は単純で、ただ元の Markdown
    ファイルの文字列を置換するだけです。"
  en: __COPY__
