baseURL = "https://inalz.netlify.com/"
title = "INALZ"

themesDir = "themes"
theme = "hugo-whisper-theme"

DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1
    [[languages.en.menu.main]]
      name = "Home"
      url = "/en/"
      weight = 1
    [[languages.en.menu.main]]
      name = "Docs"
      url = "/en/docs/"
      weight = 2
    [languages.en.params]
      homepage_button_link = '/en/docs'
      homepage_button_text = 'Read The Docs'
  [languages.ja]
    contentDir = "content/ja"
    languageName = "日本語"
    weight = 2
    [[languages.ja.menu.main]]
      name = "Home"
      url = "/ja/"
      weight = 1
    [[languages.ja.menu.main]]
      name = "Docs"
      url = "/ja/docs/"
      weight = 2
    [languages.ja.params]
      homepage_button_link = '/ja/docs'
      homepage_button_text = 'ドキュメントを読む'

[params]
  google_analytics_id=""
  # homepage_intro = 'Whisper is a documentation theme built with Hugo. The design and functionality is intentionally minimal.'
  # homepage_image = '/images/terminal.gif'

  [params.homepage_meta_tags]
    meta_description = "Inalz is markdown document 18n tool for maintainable translation"
    meta_og_title = "Inalz documentaion"
    meta_og_type = "website"
    meta_og_url = "https://inalz.netlify.com"
    # meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-whisper-theme/master/images/tn.png"
    meta_og_description = "Inalz is markdown document 18n tool for maintainable translation"
    meta_twitter_card = "summary"

  [params.logo]
      # mobile = "/images/logo-mobile.svg"
      # standard  = "/images/logo.svg"
