lang:
  source: en
  targets:
    - ja
documents:
  - linkMode: path
    source: misc/mock/config/pathMode/dir
    targets:
      ja: misc/mock/config/pathMode/ja
    locale: misc/mock/config/pathMode/locales
