lang:
  source: en
  targets:
    - ja
documents:
  - linkMode: path
    source: pathMode/doc.md
    targets:
      ja: pathMode/doc_ja.md
    locale: pathMode/locale.yml
  - linkMode: filename
    contentDir: filenameMode
    localeDir: locales
  - linkMode: directory
    contentDir: directoryMode/:lang
    localeDir: locales
