lang:
  source: en
  targets:
    - ja
documents:
  - linkMode: path
    source: pathMode/doc.md
    targets:
      ja: pathMode/doc_ja.md
    locale: pathMode/locale.yml
options:
  paragraphIgnorePatterns:
    - "^\\[!\\["
  lineIgnorePatterns:
    - "^apple"
