lang:
  source: en
  targets:
    - ja
documents:
  - source: pathMode/doc.md
    targets:
      ja: pathMode/doc_ja.md
    locale: pathMode/locale.yml
  - source: pathMode/doc.md
    targets:
      ja: pathMode/doc_ja.md
    locale: pathMode/locale.yml
