lang:
  source: en
  targets:
    - ja
documents:
  - linkMode: path
    source: misc/mock/config/pathMode/doc.md
    targets:
      ja: misc/mock/config/pathMode/doc_ja.md
    locale: misc/mock/config/pathMode/locale.yml
  - linkMode: filename
    contentDir: misc/mock/config/filenameMode
    localeDir: misc/mock/config/locales
  - linkMode: directory
    contentDir: misc/mock/config/directoryMode/:lang
    localeDir: misc/mock/config/locales
