lang:
  source: en
  targets:
    - ja
documents:
  - linkMode: path
    sourcePath: misc/mock/config/pathMode/dir
    targetPaths:
      ja: misc/mock/config/pathMode/ja
    localePath: misc/mock/config/pathMode/locales
